<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Arma extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Arma_model');
    } 

    /*
     * Listing of arma
     */
    function index()
    {
        $data['arma'] = $this->Arma_model->get_all_arma();
        
        $data['_view'] = 'arma/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new arma
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('arma_codigo','Arma Codigo','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tipoarma_id' => $this->input->post('tipoarma_id'),
				'persona_id' => $this->input->post('persona_id'),
				'usuario_id' => $this->input->post('usuario_id'),
				'estado_id' => $this->input->post('estado_id'),
				'arma_numorden' => $this->input->post('arma_numorden'),
				'arma_codigo' => $this->input->post('arma_codigo'),
				'arma_fechaingreso' => $this->input->post('arma_fechaingreso'),
				'arma_horaingreso' => $this->input->post('arma_horaingreso'),
				'arma_procedencia' => $this->input->post('arma_procedencia'),
				'arma_marca' => $this->input->post('arma_marca'),
				'arma_calibre' => $this->input->post('arma_calibre'),
				'arma_aniodotacion' => $this->input->post('arma_aniodotacion'),
				'arma_lugardotacion' => $this->input->post('arma_lugardotacion'),
				'arma_novedades' => $this->input->post('arma_novedades'),
				'arma_responsable' => $this->input->post('arma_responsable'),
				'arma_foto' => $this->input->post('arma_foto'),
            );
            
            $arma_id = $this->Arma_model->add_arma($params);
            redirect('arma/index');
        }
        else
        {
			$this->load->model('Tipo_arma_model');
			$data['all_tipo_arma'] = $this->Tipo_arma_model->get_all_tipo_arma();

			$this->load->model('Persona_model');
			$data['all_persona'] = $this->Persona_model->get_all_persona();

			$this->load->model('Usuario_model');
			$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();
            
            $data['_view'] = 'arma/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a arma
     */
    function edit($arma_id)
    {   
        // check if the arma exists before trying to edit it
        $data['arma'] = $this->Arma_model->get_arma($arma_id);
        
        if(isset($data['arma']['arma_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('arma_codigo','Arma Codigo','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tipoarma_id' => $this->input->post('tipoarma_id'),
					'persona_id' => $this->input->post('persona_id'),
					'usuario_id' => $this->input->post('usuario_id'),
					'estado_id' => $this->input->post('estado_id'),
					'arma_numorden' => $this->input->post('arma_numorden'),
					'arma_codigo' => $this->input->post('arma_codigo'),
					'arma_fechaingreso' => $this->input->post('arma_fechaingreso'),
					'arma_horaingreso' => $this->input->post('arma_horaingreso'),
					'arma_procedencia' => $this->input->post('arma_procedencia'),
					'arma_marca' => $this->input->post('arma_marca'),
					'arma_calibre' => $this->input->post('arma_calibre'),
					'arma_aniodotacion' => $this->input->post('arma_aniodotacion'),
					'arma_lugardotacion' => $this->input->post('arma_lugardotacion'),
					'arma_novedades' => $this->input->post('arma_novedades'),
					'arma_responsable' => $this->input->post('arma_responsable'),
					'arma_foto' => $this->input->post('arma_foto'),
                );

                $this->Arma_model->update_arma($arma_id,$params);            
                redirect('arma/index');
            }
            else
            {
				$this->load->model('Tipo_arma_model');
				$data['all_tipo_arma'] = $this->Tipo_arma_model->get_all_tipo_arma();

				$this->load->model('Persona_model');
				$data['all_persona'] = $this->Persona_model->get_all_persona();

				$this->load->model('Usuario_model');
				$data['all_usuario'] = $this->Usuario_model->get_all_usuario();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

                $data['_view'] = 'arma/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The arma you are trying to edit does not exist.');
    } 

    /*
     * Deleting arma
     */
    function remove($arma_id)
    {
        $arma = $this->Arma_model->get_arma($arma_id);

        // check if the arma exists before trying to delete it
        if(isset($arma['arma_id']))
        {
            $this->Arma_model->delete_arma($arma_id);
            redirect('arma/index');
        }
        else
            show_error('The arma you are trying to delete does not exist.');
    }
    
}
