<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grado_persona extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Grado_persona_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    } 

    /*
     * Listing of grado_persona
     */
    function index()
    {
        $data['grado_persona'] = $this->Grado_persona_model->get_all_grado_persona();
        
        $data['_view'] = 'grado_persona/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new grado_persona
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'grado_descripcion' => $this->input->post('grado_descripcion'),
            );
            
            $grado_persona_id = $this->Grado_persona_model->add_grado_persona($params);
            redirect('grado_persona/index');
        }
        else
        {            
            $data['_view'] = 'grado_persona/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a grado_persona
     */
    function edit($grado_id)
    {   
        // check if the grado_persona exists before trying to edit it
        $data['grado_persona'] = $this->Grado_persona_model->get_grado_persona($grado_id);
        
        if(isset($data['grado_persona']['grado_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'grado_descripcion' => $this->input->post('grado_descripcion'),
                );

                $this->Grado_persona_model->update_grado_persona($grado_id,$params);            
                redirect('grado_persona/index');
            }
            else
            {
                $data['_view'] = 'grado_persona/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The grado_persona you are trying to edit does not exist.');
    } 

    /*
     * Deleting grado_persona
     */
    function remove($grado_id)
    {
        $grado_persona = $this->Grado_persona_model->get_grado_persona($grado_id);

        // check if the grado_persona exists before trying to delete it
        if(isset($grado_persona['grado_id']))
        {
            $this->Grado_persona_model->delete_grado_persona($grado_id);
            redirect('grado_persona/index');
        }
        else
            show_error('The grado_persona you are trying to delete does not exist.');
    }
    
}
