<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Persona_model');
    } 

    /*
     * Listing of persona
     */
    function index()
    {
        $data['persona'] = $this->Persona_model->get_all_persona();
        
        $data['_view'] = 'persona/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new persona
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'grado_id' => $this->input->post('grado_id'),
				'estado_id' => $this->input->post('estado_id'),
				'tipo_id' => $this->input->post('tipo_id'),
				'persona_nombre' => $this->input->post('persona_nombre'),
				'persona_apellido' => $this->input->post('persona_apellido'),
				'persona_ci' => $this->input->post('persona_ci'),
				'persona_telefono' => $this->input->post('persona_telefono'),
				'persona_celular' => $this->input->post('persona_celular'),
				'persona_direccion' => $this->input->post('persona_direccion'),
            );
            
            $persona_id = $this->Persona_model->add_persona($params);
            redirect('persona/index');
        }
        else
        {
			$this->load->model('Grado_persona_model');
			$data['all_grado_persona'] = $this->Grado_persona_model->get_all_grado_persona();

			$this->load->model('Estado_model');
			$data['all_estado'] = $this->Estado_model->get_all_estado();

			$this->load->model('Tipo_persona_model');
			$data['all_tipo_persona'] = $this->Tipo_persona_model->get_all_tipo_persona();
            
            $data['_view'] = 'persona/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a persona
     */
    function edit($persona_id)
    {   
        // check if the persona exists before trying to edit it
        $data['persona'] = $this->Persona_model->get_persona($persona_id);
        
        if(isset($data['persona']['persona_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'grado_id' => $this->input->post('grado_id'),
					'estado_id' => $this->input->post('estado_id'),
					'tipo_id' => $this->input->post('tipo_id'),
					'persona_nombre' => $this->input->post('persona_nombre'),
					'persona_apellido' => $this->input->post('persona_apellido'),
					'persona_ci' => $this->input->post('persona_ci'),
					'persona_telefono' => $this->input->post('persona_telefono'),
					'persona_celular' => $this->input->post('persona_celular'),
					'persona_direccion' => $this->input->post('persona_direccion'),
                );

                $this->Persona_model->update_persona($persona_id,$params);            
                redirect('persona/index');
            }
            else
            {
				$this->load->model('Grado_persona_model');
				$data['all_grado_persona'] = $this->Grado_persona_model->get_all_grado_persona();

				$this->load->model('Estado_model');
				$data['all_estado'] = $this->Estado_model->get_all_estado();

				$this->load->model('Tipo_persona_model');
				$data['all_tipo_persona'] = $this->Tipo_persona_model->get_all_tipo_persona();

                $data['_view'] = 'persona/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The persona you are trying to edit does not exist.');
    } 

    /*
     * Deleting persona
     */
    function remove($persona_id)
    {
        $persona = $this->Persona_model->get_persona($persona_id);

        // check if the persona exists before trying to delete it
        if(isset($persona['persona_id']))
        {
            $this->Persona_model->delete_persona($persona_id);
            redirect('persona/index');
        }
        else
            show_error('The persona you are trying to delete does not exist.');
    }
    
}
