<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Salida_armamento extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Salida_armamento_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }

    /*
     * Listing of registro
     */
    function index()
    {
        $data['registro'] = $this->Salida_armamento_model->get_all_registro();
        
        $data['_view'] = 'salida_armamento/index';
        $this->load->view('layouts/main',$data);
    }
    
    function buscar_porcodigo()  
    {
        $codigo = $this->input->post('codigo');
        $this->load->model('Arma_model');
        $arma = $this->Arma_model->getarma_porcodigo($codigo);

        if (sizeof($arma)>0){ //si encontro el producto por el codigo de producto
            echo json_encode($arma);
        }else{
            echo json_encode("no");
        }            

    }
    
}
