<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Grado_persona_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get grado_persona by grado_id
     */
    function get_grado_persona($grado_id)
    {
        $grado_persona = $this->db->query("
            SELECT
                *

            FROM
                `grado_persona`

            WHERE
                `grado_id` = ?
        ",array($grado_id))->row_array();

        return $grado_persona;
    }
        
    /*
     * Get all grado_persona
     */
    function get_all_grado_persona()
    {
        $grado_persona = $this->db->query("
            SELECT
                *

            FROM
                `grado_persona`

            WHERE
                1 = 1

            ORDER BY `grado_id` DESC
        ")->result_array();

        return $grado_persona;
    }
        
    /*
     * function to add new grado_persona
     */
    function add_grado_persona($params)
    {
        $this->db->insert('grado_persona',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update grado_persona
     */
    function update_grado_persona($grado_id,$params)
    {
        $this->db->where('grado_id',$grado_id);
        return $this->db->update('grado_persona',$params);
    }
    
    /*
     * function to delete grado_persona
     */
    function delete_grado_persona($grado_id)
    {
        return $this->db->delete('grado_persona',array('grado_id'=>$grado_id));
    }
}
