<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Persona_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get persona by persona_id
     */
    function get_persona($persona_id)
    {
        $persona = $this->db->query("
            SELECT
                *

            FROM
                `persona`

            WHERE
                `persona_id` = ?
        ",array($persona_id))->row_array();

        return $persona;
    }
        
    /*
     * Get all persona
     */
    function get_all_persona()
    {
        $persona = $this->db->query("
            SELECT
                *

            FROM
                `persona`

            WHERE
                1 = 1

            ORDER BY `persona_id` DESC
        ")->result_array();

        return $persona;
    }
        
    /*
     * function to add new persona
     */
    function add_persona($params)
    {
        $this->db->insert('persona',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update persona
     */
    function update_persona($persona_id,$params)
    {
        $this->db->where('persona_id',$persona_id);
        return $this->db->update('persona',$params);
    }
    
    /*
     * function to delete persona
     */
    function delete_persona($persona_id)
    {
        return $this->db->delete('persona',array('persona_id'=>$persona_id));
    }
    
    function get_all_persona_activa()
    {
        $persona = $this->db->query("
            SELECT
                *
            FROM
                `persona`
            WHERE
                estado_id = 1
            ORDER BY `persona_apellido` ASC, `persona_nombre` ASC
        ")->result_array();

        return $persona;
    }
}
