<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Registro_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get registro by registro_id
     */
    function get_registro($registro_id)
    {
        $registro = $this->db->query("
            SELECT
                *

            FROM
                `registro`

            WHERE
                `registro_id` = ?
        ",array($registro_id))->row_array();

        return $registro;
    }
        
    /*
     * Get all registro
     */
    function get_all_registro()
    {
        $registro = $this->db->query(
        "SELECT r.*, p.persona_apellido,p.persona_nombre , a.arma_codigo, tp.tipo_descripcion, ta.tipoarma_descripcion 
        from registro r 
        left join persona p on r.persona_id = p.persona_id 
        left join arma a on r.arma_id = a.arma_id
        left join tipo_arma ta on ta.tipoarma_id =a.tipoarma_id 
        left join tipo_persona tp on tp.tipo_id = p.tipo_id 
        where 1 = 1
        ")->result_array();

        return $registro;
    }
        
    /*
     * function to add new registro
     */
    function add_registro($params)
    {
        $this->db->insert('registro',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update registro
     */
    function update_registro($registro_id,$params)
    {
        $this->db->where('registro_id',$registro_id);
        return $this->db->update('registro',$params);
    }
    
    /*
     * function to delete registro
     */
    function delete_registro($registro_id)
    {
        return $this->db->delete('registro',array('registro_id'=>$registro_id));
    }
    
    /*
     * comprobante
     */
    function get_comprobante($registro_id)
    {
        $sql = "SELECT 
                r.*,
                d.*,
                a.*,
                e.estado_descripcion,
                p.*,
                t.tipoarma_descripcion,
                ee.estado_descripcion as estado_arma,
                e.estado_descripcion as estado_prestamo,
                u.usuario_nombre,
                gp.grado_descripcion
              FROM
                registro r
                
                LEFT OUTER JOIN detalle_registro d ON (d.registro_id = r.registro_id)
                LEFT OUTER JOIN persona p ON (p.persona_id = r.registro_id)
                LEFT OUTER JOIN estado e ON (e.estado_id = d.estado_id)
                LEFT OUTER JOIN arma a ON (a.arma_id = d.arma_id)
                LEFT OUTER JOIN tipo_arma t ON (t.tipoarma_id = a.tipoarma_id)
                LEFT OUTER JOIN estado ee ON (ee.estado_id = a.estado_id)
                LEFT OUTER JOIN usuario u ON (u.usuario_id = r.usuario_id)
                left outer join grado_persona gp on (gp.grado_id = p.grado_id)
              WHERE
                r.registro_id = ".$registro_id;
        
        return $this->db->query($sql)->result_array();   
             
    }
    
    function get_historial($persona_id, $arma_id)
    {
        $sql = "SELECT 
                r.*,
                d.*,
                a.*,
                e.estado_descripcion,
                p.*,
                t.tipoarma_descripcion,
                ee.estado_descripcion as estado_arma,
                e.estado_descripcion as estado_prestamo,
                u.usuario_nombre
              FROM
                registro r
                
                LEFT OUTER JOIN detalle_registro d ON (d.registro_id = r.registro_id)
                LEFT OUTER JOIN persona p ON (p.persona_id = r.registro_id)
                LEFT OUTER JOIN estado e ON (e.estado_id = r.estado_id)
                LEFT OUTER JOIN arma a ON (a.arma_id = d.arma_id)
                LEFT OUTER JOIN tipo_arma t ON (t.tipoarma_id = a.tipoarma_id)
                LEFT OUTER JOIN estado ee ON (ee.estado_id = a.estado_id)
                LEFT OUTER JOIN usuario u ON (u.usuario_id = r.usuario_id)


              WHERE
                p.persona_id = ".$persona_id.
                " and a.arma_id = ".$arma_id.
                " order by r.registro_fechasalida desc";
        
        return $this->db->query($sql)->result_array();   
             
    }

    function get_registro_impresion($registro_id){
        return $this->db->query(
            "SELECT r.*, p.*, a.*,ta.tipoarma_descripcion, tp.tipo_descripcion 
            from registro r 
            left join persona p on r.persona_id = p.persona_id 
            left join arma a on r.arma_id = a.arma_id 
            left join tipo_arma ta on a.tipoarma_id = ta.tipoarma_id 
            left join tipo_persona tp on tp.tipo_id = p.tipo_id 
            where 1=1
            and r.registro_id = $registro_id"
        )->row_array();
    }

    function get_all_registros($persona_id){
        return $this->db->query(
            "SELECT r.*, e.estado_color
            from registro r 
            left join persona p on r.persona_id = p.persona_id
            left join estado e on r.estado_id = e.estado_id 
            where 1=1
            and r.estado_id = 5
            and r.persona_id = $persona_id"
        )->result_array();
    }

    function get_all_detalleregistro($registro_id){
        return $this->db->query(
            "SELECT dr.*, a.*,p.*,ta.tipoarma_descripcion,r.registro_id,r.registro_fechasalida,r.registro_horasalida, e.estado_color
            from detalle_registro dr 
            left join registro r on dr.registro_id = r.registro_id 
            left join persona p on p.persona_id = r.persona_id 
            left join arma a on dr.arma_id = a.arma_id
            left join tipo_arma ta on ta.tipoarma_id = a.tipoarma_id 
            left join estado e on dr.estado_id = e.estado_id 
            where 1=1
            and dr.registro_id = $registro_id
            order by a.arma_codigo asc"
        )->result_array();
    }

    function update_detregistro($detregistro_id, $params){
        $this->db->where('detregistro_id',$detregistro_id);
        return $this->db->update('detalle_registro',$params);
    }

    function get_armas_pendientes_entregar($persona_id){
        return $this->db->query(
            "SELECT dr.*,r.*, a.arma_codigo , ta.tipoarma_descripcion 
            from detalle_registro dr 
            left join arma a on dr.arma_id = a.arma_id 
            left join registro r on dr.registro_id = r.registro_id 
            left join estado e on dr.estado_id  = e.estado_id 
            left join persona p on r.persona_id  = p.persona_id 
            left join tipo_arma ta on a.tipoarma_id = ta.tipoarma_id 
            where 1=1
            and r.estado_id = 6
            and dr.estado_id = 5
            and p.persona_id = $persona_id"
        )->result_array();
    }
    function get_detalle_registro2($detregistro_id){
        return $this->db->query(
            "SELECT dr.*,r.*,a.arma_codigo,a.arma_foto, ta.tipoarma_descripcion,p.*
            from detalle_registro dr 
            left join arma a on  dr.arma_id = a.arma_id 
            left join registro r on r.registro_id = dr.registro_id 
            left join persona p on p.persona_id = r.persona_id 
            left join tipo_arma ta on a.tipoarma_id = ta.tipoarma_id 
            where 1=1
            and dr.detregistro_id  = $detregistro_id"
        )->result_array();
    }
    function add_imagen($params){
        $this->db->insert('imagen',$params);
        return $this->db->insert_id();        
    }
}
